# theme: jekyll-theme-midnight

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Top Trends from Social Media]
description: [Get the latest trends of a variety of products from social media]